model: default

framework: pytorch
storage:
  storage_type: "daos_pytorch"
  storage_root: "/"

workflow:
  generate_data: False
  train: True
  evaluation: True
  profiling: False

dataset:
  data_folder: /data/default
  format: npz
  num_files_train: 64
  num_files_eval: 8
  num_samples_per_file: 1
  record_length: 4096
  num_subfolders_train: 2
  num_subfolders_eval: 2
  daos_pool: torch
  daos_cont: torch


reader:
  data_loader: daos_pytorch
  batch_size: 4
  batch_size_eval: 1

checkpoint:
  checkpoint_folder: /checkpoints
  checkpoint_daos_pool: torch
  checkpoint_daos_cont: torch
  checkpoint_mechanism_classname: dlio_benchmark.checkpointing.pydaos_checkpointing.PyDaosTorchCheckpointing

train:
  epochs: 10
  computation_time: 0.10


evaluation:
  eval_time: 0.5
  epochs_between_evals: 1

profiling:
  profiler: iostat
